### ISSUE TITLE
Ca2+ ion in the binding pocket

### ISSUE THREAD

**Issue by CLG68** [molecularmodelinglab/banana#2]
Hi,

Thank you for this nice tool.  I tested it with different types of targets and it works very well.  However, one target I'm interested to use for a screening, does not show enrichment of known ligands using BANANA.  This receptor needs a Ca2+ ion to bind its ligand as shown in the pdb: 6W25 & 7F58.  A water molecule could also be involved in ligand binding so I created 3 binding pockets, one with Ca2+ and water, one with just Ca2+ and one w/o Ca2+/Water.  I used 41 known ligands including those in the pdb and added them to my library of 11.2M smiles.
I just left the water molecule and Ca2+ as is in the pdb.  Do I need to edit the pdb?  Is it possible to screen using BANANA in pockets containing ions?

thanks for your help

**Comment by mixarcid** [comment]
Sorry about the late reply -- I just realized I don't get notifications for this repo :facepalm:
At the moment banana just ignores any non-amino-acid residue in the PDB file -- so you can keep it in but alas it will not matter for banana's prediction.

You are definitely right that ions in the binding site can really matter -- I will keep this in mind for future work.
